# ruby encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Country.create(name: 'Germany')
Country.create(name: 'Canada')

City.create(name: 'Argyle')
City.create(name: 'Arviat')
City.create(name: 'Baddeck')
City.create(name: 'Baie-Comeau')
City.create(name: 'Baie-d\'Urfé')
City.create(name: 'Banff')
City.create(name: 'Berwick')
City.create(name: 'Bonavista')
City.create(name: 'Brandon')
City.create(name: 'Burns Lake')
City.create(name: 'Calder')
City.create(name: 'Cambridge Bay')
City.create(name: 'Canmore')
City.create(name: 'Canora')
City.create(name: 'Cape Breton Island')
City.create(name: 'Carbonear')
City.create(name: 'Carleton')
City.create(name: 'Carlton')
City.create(name: 'Chambord')
City.create(name: 'Charlottetown')
City.create(name: 'Chilliwack')
City.create(name: 'Coleville Lake')
City.create(name: 'Cranbrook')
City.create(name: 'Cumberland County')
City.create(name: 'Daly')
City.create(name: 'Edmonton')
City.create(name: 'Fort Providence')
City.create(name: 'Gander')
City.create(name: 'Gjoa Haven')
City.create(name: 'Glendon')
City.create(name: 'Grand Falls')
City.create(name: 'Guelph')
City.create(name: 'Hudson Bay')
City.create(name: 'Iqaluit')
City.create(name: 'Jasper')
City.create(name: 'Kent')
City.create(name: 'Kitchener')
City.create(name: 'Lakeland County')
City.create(name: 'Langenburg')
City.create(name: 'McCallum')
City.create(name: 'Minitonas')
City.create(name: 'Moncton')
City.create(name: 'Montague')
City.create(name: 'Montpellier')
City.create(name: 'Moose Jaw')
City.create(name: 'Mount Pearl')
City.create(name: 'Mundare')
City.create(name: 'Municipal District')
City.create(name: 'New Maryland')
City.create(name: 'Pangnirtung')
City.create(name: 'Paulatuk')
City.create(name: 'Port Alice')
City.create(name: 'Price')
City.create(name: 'Quispamsis')
City.create(name: 'Rae-Edzo')
City.create(name: 'Regina')
City.create(name: 'Sachs Harbour')
City.create(name: 'Scarborough')
City.create(name: 'Saint-André-lez-Lille')
City.create(name: 'Shippagan')
City.create(name: 'Smithers')
City.create(name: 'Stonewall')
City.create(name: 'Stratford')
City.create(name: 'Strathcona County')
City.create(name: 'Tracadie-Shelia')
City.create(name: 'Tsiigehtchic')
City.create(name: 'Tulita')
City.create(name: 'Tumbler Ridge')
City.create(name: 'Vegreville')
City.create(name: 'Ville de Maniwaki')
City.create(name: 'Watson Lake')
City.create(name: 'Weyburn')
City.create(name: 'Whitby')
City.create(name: 'Whitehorse')
City.create(name: 'Windsor')
City.create(name: 'Winnipeg')
City.create(name: 'Wolfville')
City.create(name: 'Wrigley')
City.create(name: 'Yorkton')

Person.create(:name => 'Yorkton')
